services:
  - type: web
    name: your-app-name
    env: docker
    buildCommand: "rm -rf bootstrap/cache/*.php && php artisan config:clear && php artisan cache:clear && composer install --no-dev --optimize-autoloader && php artisan migrate --force && npm install && npm run build"